routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\User\CommentController;
use App\Http\Controllers\User\PostController as UserPostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', [MainController::class, 'index'])->name('main.page');
Route::get('/post/{post}', [MainController::class, 'show'])->name('main.show');
Route::get('/category/{category}', CategoryController::class)->name('main.category');

// Admin routes
Route::prefix('/admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::resource('/post', AdminPostController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/category', AdminCategoryController::class);
});

// User routes
Route::prefix('/user')->name('user.')->middleware(['auth', 'role:user'])->group(function () {
    Route::resource('/post', UserPostController::class);
    Route::post('/comment/store/{post}', CommentController::class)->name('comment.store');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['title'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = Category::paginate(10);

        return view('admin.category.index')->with('categories', $categories);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {

        $validated = $request->validate([
            'title' => 'required|max:120',
        ]);

        Category::create($validated);

        return redirect()->route('admin.category.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category)
    {
        $posts = $category->posts()->orderBy('created_at', 'DESC')->paginate(10);

        return view('admin.category.show')->with(['category' => $category, 'posts' => $posts]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {
        return view('admin.category.edit')->with('category', $category);

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Category $category)
    {
        if (auth()->user()->cannot('admin')) {
            abort(403);
        }

        $validated = $request->validate([
            'title' => 'required|max:120',
        ]);

        $category->update($validated);

        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category)
    {
        if (auth()->user()->cannot('admin', $category)) {
            abort(403);
        }

        $category->delete();

        return redirect()->route('admin.category.index');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(string $id)
    {
        $categories = Category::all();
        $posts = Post::where('category_id', $id)->orderBy('created_at', 'DESC')->paginate(3);
        $selected_category = $categories->firstWhere('id', $id);
        //        dd($selected_category);
        return view('main.by-categories')->with(['categories' => $categories, 'posts' => $posts, 'selected_category' => $selected_category]);
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card border border-secondary">
                    <div class="card-header bg-danger-subtle border-danger">{{ __('Create post category') }}</div>

                    <div class="card-body">
                        <form action="{{ route('admin.category.store') }}" method="post">
                            @csrf
                            <div class="mb-3 col-sm-6">
                                <label for="title" class="form-label">Title</label>
                                <input name="title" type="text" class="form-control" id="title">
                                @error('title')
                                <div class="text-danger">Enter title</div>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-outline-success">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit category') }}</div>

                    <div class="card-body">
                        <form action="{{ route('admin.category.update', $category) }}" method="post">
                            @method('put')
                            @csrf
                            <div class="mb-3 col-sm-6">
                                <label for="title" class="form-label">Title</label>
                                <input name="title" type="text" class="form-control" id="title"
                                       value="{{ @old('title', $category->title) }}">
                                @error('title')
                                <div class="text-danger">Title should be</div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card border border-secondary">
                    <div class="card-header bg-danger-subtle border-danger">{{ __('All categories') }}</div>

                    <div class="card-body">
                        <div class="container py-2">

                            <a href="{{ route('admin.category.create') }}" class="btn btn-outline-secondary">Add new
                                category</a>

                            @if(!$categories->isEmpty())
                                <div class="my-2 p-2 border-b border-gray-200 w-50 sm:rounded-lg mt-2">
                                    <table class="table table-hover mt-2 table table-sm">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($categories as $category)
                                            <tr>
                                                <td>{{ $category->id }}</td>
                                                <td>{{ $category->title }}</td>
                                                <td>
                                                    <form action="{{ route('admin.category.destroy', $category) }}"
                                                          method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <a href="{{ route('admin.category.show', $category) }}"
                                                           class="me-2 btn btn-outline-success btn-sm">
                                                            See
                                                        </a>
                                                        <a href="{{ route('admin.category.edit', $category) }}"
                                                           class="me-2 btn btn-outline-primary btn-sm">
                                                            Edit
                                                        </a>
                                                        <button type="submit" class="btn btn-outline-danger btn-sm"
                                                                onclick=" return confirm('Are you sure you wish to delete this category ?')">
                                                            Delete
                                                        </button>

                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                {{ $categories->links() }}
                            @else
                                <p class="mt-4">You have not created categories yet</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/admin/category/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card border border-secondary">

                    <div class="card-header bg-danger-subtle border-danger">
                        <a class="fw-bold link-dark text-decoration-none" href="{{ url()->previous() }}">
                            Back</a> &nbsp;/ &nbsp;Category
                    </div>

                    <div class="card-body">
                        <div class="container py-4">

                            <h1 class="text-body-emphasis">{{ $category->title }}</h1>
                            <p>
                                <strong>Posted: </strong> {{ $category->created_at->format('jS M') }}
                            </p>

                            @if(!$posts->isEmpty())
                                <div class="my-2 p-2 border-b border-gray-200 w-50 sm:rounded-lg mt-2">
                                    <table class="table table-hover mt-2 table table-sm">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($posts as $post)
                                            <tr>
                                                <td>{{ $post->id }}</td>
                                                <td>{{ $post->title }}</td>
                                                <td>
                                                    <form action="{{ route('admin.post.destroy', $post) }}"
                                                          method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <a href="{{ route('admin.post.show', $post) }}"
                                                           class="me-2 btn btn-outline-success btn-sm">
                                                            See
                                                        </a>
                                                        <a href="{{ route('admin.post.edit', $post) }}"
                                                           class="me-2 btn btn-outline-primary btn-sm">
                                                            Edit
                                                        </a>
                                                        <button type="submit" class="btn btn-outline-danger btn-sm"
                                                                onclick=" return confirm('Are you sure you wish to delete this post ?')">
                                                            Delete
                                                        </button>

                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                {{ $posts->links() }}
                            @else
                                <p class="mt-4">You have not created categories yet</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection