routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\User\CommentController;
use App\Http\Controllers\User\PostController as UserPostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', [MainController::class, 'index'])->name('main.page');
Route::get('/post/{post}', [MainController::class, 'show'])->name('main.show');
Route::get('/category/{category}', CategoryController::class)->name('main.category');

// Admin routes
Route::prefix('/admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::resource('/post', AdminPostController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/category', AdminCategoryController::class);
});

// User routes
Route::prefix('/user')->name('user.')->middleware(['auth', 'role:user'])->group(function () {
    Route::resource('/post', UserPostController::class);
    Route::post('/comment/store/{post}', CommentController::class)->name('comment.store');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">

        @include('layouts.navigation')

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/navigation.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav me-auto">
                <a href="{{ route('main.category', 1) }}" class="nav-link ms-2 {{ request()->routeIs('main.category') ? 'active link-success' : '' }}">By categories</a>

            @can('user')
                <a href="{{ route('user.post.index') }}" class="nav-link ms-2 {{ request()->routeIs('user.post.index') ? 'active link-success' : '' }}">All my Posts</a>
                <a href="{{ route('user.post.create') }}" class="nav-link ms-2 {{ request()->routeIs('user.post.create') ? 'active link-success' : '' }}">Create Post</a>
                @endcan

                @can('admin')
                <a href="{{ route('admin.post.index') }}" class="nav-link ms-2 {{ request()->routeIs('admin.post.index') ? 'active link-success' : '' }}">All my Posts</a>
                <a href="{{ route('admin.post.create') }}" class="nav-link ms-2 {{ request()->routeIs('admin.post.create') ? 'active link-success' : '' }}">Create Post</a>
                <a href="{{ route('admin.category.index') }}" class="nav-link ms-2 {{ request()->routeIs('admin.category.index') ? 'active link-danger' : '' }}">Post Categories</a>
                <a href="{{ route('admin.user.index') }}" class="nav-link ms-2 {{ request()->routeIs('admin.user.index') ? 'active link-danger' : '' }}">All Users</a>
                @endcan
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ms-auto">
                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @endif

                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>