routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\User\CommentController;
use App\Http\Controllers\User\PostController as UserPostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', [MainController::class, 'index'])->name('main.page');
Route::get('/post/{post}', [MainController::class, 'show'])->name('main.show');
Route::get('/category/{category}', CategoryController::class)->name('main.category');

// Admin routes
Route::prefix('/admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::resource('/post', AdminPostController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/category', AdminCategoryController::class);
});

// User routes
Route::prefix('/user')->name('user.')->middleware(['auth', 'role:user'])->group(function () {
    Route::resource('/post', UserPostController::class);
    Route::post('/comment/store/{post}', CommentController::class)->name('comment.store');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class, 'author_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, 'author_id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::paginate(10);

        return view('admin.user.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:120',
            'email' => 'required|max:120',
            'role' => 'required|not_in:0',
            'password' => 'required',
        ]);

        $validated['password'] = Hash::make($validated['password']);

        User::create($validated);

        return redirect()->route('admin.user.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(User $user)
    {
        $posts = $user->posts()->orderBy('created_at', 'DESC')->paginate(10);

        return view('admin.user.show')->with(['user' => $user, 'posts' => $posts]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        return view('admin.user.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, User $user)
    {
        if (auth()->user()->cannot('admin')) {
            abort(403);
        }

        $validated = $request->validate([
            'name' => 'required|max:120',
            'email' => 'required|max:120',
            'role' => 'required|not_in:0',
        ]);

        $user->update($validated);

        return to_route('admin.user.show', $user);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user)
    {
        if (auth()->user()->cannot('admin')) {
            abort(403);
        }

        $user->delete();

        return redirect()->route('admin.user.index');
    }
}

app/Http/Controllers/User/CommentController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request, Post $post)
    {
        if (auth()->user()->cannot('user', $post)) {
            return redirect()->route('main.show', $post)
                ->with('warning', 'Please log in to leave a comment.');
        }

        $request->merge([
            'author_id' => auth()->id(),
            'post_id' => $post->id,
        ]);

        $validated = $request->validate([
            'author_id' => 'required',
            'post_id' => 'required',
            'text' => 'required',
        ]);

        Comment::create($validated);

        return redirect()->route('main.show', $post);
    }
}

app/Http/Controllers/User/PostController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $posts = auth()->user()->posts()->orderBy('created_at', 'DESC')->paginate(6);

        return view('user.post.index')->with('posts', $posts);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();

        return view('user.post.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->merge([
            'author_id' => auth()->id(),
        ]);

        $validated = $request->validate([
            'author_id' => 'required',
            'title' => 'required|max:120',
            'category_id' => 'required|not_in:0',
            'text' => 'required',
        ]);

        Post::create($validated);

        return redirect()->route('user.post.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Post $post)
    {
        if (auth()->user()->cannot('author', $post)) {
            abort(403);
        }
        $comments = $post->comments()->with('author')->orderBy('created_at', 'DESC')->paginate(10);

        return view('user.post.show')->with(['post' => $post, 'comments' => $comments]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Post $post)
    {
        if (auth()->user()->cannot('author', $post)) {
            abort(403);
        }

        $categories = Category::all();

        return view('user.post.edit')->with(['post' => $post, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Post $post)
    {
        if (auth()->user()->cannot('author', $post)) {
            abort(403);
        }

        $validated = $request->validate([
            'title' => 'required|max:120',
            'category_id' => 'required|not_in:0',
            'text' => 'required',
        ]);

        $post->update($validated);

        return to_route('user.post.show', $post);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Post $post)
    {
        if (auth()->user()->cannot('author', $post)) {
            abort(403);
        }

        $post->delete();

        return redirect()->route('user.post.index');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border border-secondary">
                <div class="card-header bg-danger-subtle border-danger">{{ __('Create user') }}</div>

                <div class="card-body">
                    <form action="{{ route('admin.user.store') }}" method="post">
                        @csrf
                        <div class="mb-3 col-sm-6">
                            <label for="name" class="form-label">Name</label>
                            <input name="name" type="text" class="form-control" id="name">
                            @error('name')
                            <div class="text-danger">Inter name</div>
                            @enderror
                        </div>
                        <div class="mb-3 col-sm-6">
                            <label for="email" class="form-label">Email</label>
                            <input name="email" type="email" class="form-control" id="email">
                            @error('email')
                            <div class="text-danger">Inter email</div>
                            @enderror
                        </div>
                        <div class="mb-3 ">
                            <select name="role" class="form-select" aria-label="Select user role">
                                <option value="0">Select user role</option>
                                <option
                                    value="user" {{ @old('role') === 'user' ? "selected" : "" }}>user
                                </option>
                                <option
                                    value="admin" {{ @old('role') === 'admin' ? "selected" : "" }}>admin
                                </option>
                            </select>
                            @error('role')
                            <div class="text-danger">Select role</div>
                            @enderror
                        </div>
                        <div class="mb-3 col-sm-6">
                            <label for="password" class="form-label">Password</label>
                            <input name="password" type="text" class="form-control" id="password">
                            @error('password')
                            <div class="text-danger">Inter password</div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-outline-success">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card border border-secondary">
                    <div class="card-header bg-danger-subtle border-danger">{{ __('Edit user') }}</div>

                    <div class="card-body">
                        <form action="{{ route('admin.user.update', $user) }}" method="post">
                            @method('put')
                            @csrf
                            <div class="mb-3 col-sm-6">
                                <label for="name" class="form-label">Title</label>
                                <input name="name" type="text" class="form-control" id="name"
                                       value="{{ @old('name', $user->name) }}">
                                @error('name')
                                <div class="text-danger">Enter name</div>
                                @enderror
                            </div>

                            <div class="mb-3 col-sm-6">
                                <label for="email" class="form-label">Email</label>
                                <input name="email" type="email" class="form-control" id="email"
                                       value="{{ @old('email', $user->email) }}">
                                @error('email')
                                <div class="text-danger">Enter email</div>
                                @enderror
                            </div>

                            <div class="mb-3 ">
                                <select name="role" class="form-select" aria-label="Select user role">
                                    <option value="0">Select user role</option>
                                    <option
                                        value="user" {{ @old('role', $user->role) === 'user' ? "selected" : "" }}>user
                                    </option>
                                    <option
                                        value="admin" {{ @old('role', $user->role) === 'admin' ? "selected" : "" }}>admin
                                    </option>
                                </select>
                                @error('role')
                                <div class="text-danger">Select role</div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-outline-success">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card border border-secondary">
                <div class="card-header bg-danger-subtle border-danger">{{ __('All users') }}</div>

                <div class="card-body">
                    <div class="container py-2">

                        <a href="{{ route('admin.user.create') }}" class="btn btn-outline-secondary">+ Add new user</a>

                        @if(!$users->isEmpty())
                        <div class="my-2 p-2 border-b border-gray-200 w-50 sm:rounded-lg mt-2">
                            <table class="table table-hover mt-2 table table-sm">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <td>{{ $user->id }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>
                                            <form action="{{ route('admin.user.destroy', $user) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <a href="{{ route('admin.user.show', $user) }}"
                                                   class="me-2 btn btn-outline-success btn-sm">
                                                    See
                                                </a>
                                                <a href="{{ route('admin.user.edit', $user) }}"
                                                   class="me-2 btn btn-outline-primary btn-sm">
                                                    Edit
                                                </a>
                                                <button type="submit" class="btn btn-outline-danger btn-sm"
                                                        onclick=" return confirm('Are you sure you wish to delete this user and all it posts and comments ?')">
                                                    Delete
                                                </button>

                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{ $users->links() }}
                        @else
                            <p class="mt-4">No users have been created yet</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card border border-secondary">

                <div class="card-header bg-danger-subtle border-danger"><a
                        class="fw-bold link-dark text-decoration-none" href="{{ url()->previous() }}">
                        Back</a> &nbsp;/ &nbsp;My post
                </div>

                <div class="card-body">
                    <div class="container py-2">

                        <h1 class="text-body-emphasis">Name: {{ $user->name }}</h1>
                        <h4>
                            <strong>Registered: </strong> {{ $user->created_at->diffForHumans() }}
                        </h4>
                        <h4>
                            <strong>Email: </strong> {{ $user->email }}
                        </h4>
                        <h4>
                            <strong>Role: </strong> {{ $user->role }}
                        </h4>

                        @if(!$posts->isEmpty())
                            <div class="my-2 p-2 border-b border-gray-200 w-50 sm:rounded-lg mt-2">
                                <table class="table table-hover mt-2 table table-sm">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($posts as $post)
                                        <tr>
                                            <td>{{ $post->id }}</td>
                                            <td>{{ $post->title }}</td>
                                            <td>
                                                <form action="{{ route('admin.post.destroy', $post) }}"
                                                      method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a href="{{ route('admin.post.show', $post) }}"
                                                       class="me-2 btn btn-outline-success btn-sm">
                                                        See
                                                    </a>
                                                    <a href="{{ route('admin.post.edit', $post) }}"
                                                       class="me-2 btn btn-outline-primary btn-sm">
                                                        Edit
                                                    </a>
                                                    <button type="submit" class="btn btn-outline-danger btn-sm"
                                                            onclick=" return confirm('Are you sure you wish to delete this post ?')">
                                                        Delete
                                                    </button>

                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            {{ $posts->links() }}
                        @else
                            <p  class="mt-4">User has no posts</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection