routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\User\CommentController;
use App\Http\Controllers\User\PostController as UserPostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', [MainController::class, 'index'])->name('main.page');
Route::get('/post/{post}', [MainController::class, 'show'])->name('main.show');
Route::get('/category/{category}', CategoryController::class)->name('main.category');

// Admin routes
Route::prefix('/admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::resource('/post', AdminPostController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/category', AdminCategoryController::class);
});

// User routes
Route::prefix('/user')->name('user.')->middleware(['auth', 'role:user'])->group(function () {
    Route::resource('/post', UserPostController::class);
    Route::post('/comment/store/{post}', CommentController::class)->name('comment.store');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['author_id', 'category_id', 'title', 'text'];

    public function author()
    {
        return $this->belongsTo(User::class, 'author_id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Models/PostType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PostType extends Model
{
    use HasFactory;

    protected $fillable = ['title'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class, 'author_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, 'author_id');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $posts = auth()->user()->posts()->orderBy('created_at', 'DESC')->paginate(10);

        return view('admin.post.index')->with('posts', $posts);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();

        return view('admin.post.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->merge([
            'author_id' => auth()->id(),
        ]);

        $validated = $request->validate([
            'author_id' => 'required',
            'title' => 'required|max:120',
            'category_id' => 'required|not_in:0',
            'text' => 'required',
        ]);

        Post::create($validated);

        return redirect()->route('admin.post.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Post $post)
    {
        if (auth()->user()->cannot('admin')) {
            return redirect()->route('main.show-post', $post)
                ->with('warning', 'Please log in to leave a comment.');
        }
        $comments = $post->comments()->with('author')->orderBy('created_at', 'DESC')->paginate(10);

        return view('admin.post.show')->with(['post' => $post, 'comments' => $comments]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Post $post)
    {
        if (auth()->user()->cannot('admin')) {
            abort(403);
        }

        $categories = Category::all();

        return view('admin.post.edit')->with(['post' => $post, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Post $post)
    {
        if (auth()->user()->cannot('admin')) {
            abort(403);
        }

        $validated = $request->validate([
            'title' => 'required|max:120',
            'category_id' => 'required|not_in:0',
            'text' => 'required',
        ]);

        $post->update($validated);

        return to_route('admin.post.show', $post);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Post $post) //this will be if in all posts
    {
        if (auth()->user()->cannot('admin')) {
            abort(403);
        }

        $post->delete();

        return redirect()->route('main.page');
    }

    public function destroyPublic(Post $post) // this will be if in user
    {
        if (auth()->user()->cannot('admin')) {
            abort(403);
        }

        $post->delete();

        return redirect()->route('main.page');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::paginate(10);

        return view('admin.user.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:120',
            'email' => 'required|max:120',
            'role' => 'required|not_in:0',
            'password' => 'required',
        ]);

        $validated['password'] = Hash::make($validated['password']);

        User::create($validated);

        return redirect()->route('admin.user.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(User $user)
    {
        $posts = $user->posts()->orderBy('created_at', 'DESC')->paginate(10);

        return view('admin.user.show')->with(['user' => $user, 'posts' => $posts]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        return view('admin.user.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, User $user)
    {
        if (auth()->user()->cannot('admin')) {
            abort(403);
        }

        $validated = $request->validate([
            'name' => 'required|max:120',
            'email' => 'required|max:120',
            'role' => 'required|not_in:0',
        ]);

        $user->update($validated);

        return to_route('admin.user.show', $user);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user)
    {
        if (auth()->user()->cannot('admin')) {
            abort(403);
        }

        $user->delete();

        return redirect()->route('admin.user.index');
    }
}

app/Http/Controllers/User/CommentController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request, Post $post)
    {
        if (auth()->user()->cannot('user', $post)) {
            return redirect()->route('main.show', $post)
                ->with('warning', 'Please log in to leave a comment.');
        }

        $request->merge([
            'author_id' => auth()->id(),
            'post_id' => $post->id,
        ]);

        $validated = $request->validate([
            'author_id' => 'required',
            'post_id' => 'required',
            'text' => 'required',
        ]);

        Comment::create($validated);

        return redirect()->route('main.show', $post);
    }
}

app/Http/Controllers/User/PostController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $posts = auth()->user()->posts()->orderBy('created_at', 'DESC')->paginate(6);

        return view('user.post.index')->with('posts', $posts);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();

        return view('user.post.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->merge([
            'author_id' => auth()->id(),
        ]);

        $validated = $request->validate([
            'author_id' => 'required',
            'title' => 'required|max:120',
            'category_id' => 'required|not_in:0',
            'text' => 'required',
        ]);

        Post::create($validated);

        return redirect()->route('user.post.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Post $post)
    {
        if (auth()->user()->cannot('author', $post)) {
            abort(403);
        }
        $comments = $post->comments()->with('author')->orderBy('created_at', 'DESC')->paginate(10);

        return view('user.post.show')->with(['post' => $post, 'comments' => $comments]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Post $post)
    {
        if (auth()->user()->cannot('author', $post)) {
            abort(403);
        }

        $categories = Category::all();

        return view('user.post.edit')->with(['post' => $post, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Post $post)
    {
        if (auth()->user()->cannot('author', $post)) {
            abort(403);
        }

        $validated = $request->validate([
            'title' => 'required|max:120',
            'category_id' => 'required|not_in:0',
            'text' => 'required',
        ]);

        $post->update($validated);

        return to_route('user.post.show', $post);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Post $post)
    {
        if (auth()->user()->cannot('author', $post)) {
            abort(403);
        }

        $post->delete();

        return redirect()->route('user.post.index');
    }
}

resources/views/user/post/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card border border-success">
                    <div class="card-header bg-success-subtle border-success">{{ __('Create post') }}</div>

                    <div class="card-body">
                        <div class="container py-1">

                            <form action="{{ route('user.post.store') }}" method="post">
                                @csrf
                                <div class="mb-3 col-sm-6">
                                    <label for="title" class="form-label">Title</label>
                                    <input name="title" type="text" class="form-control" id="title">
                                    @error('title')
                                    <div class="text-danger">Title should be</div>
                                    @enderror
                                </div>
                                <div class="mb-3 ">
                                    <select name="category_id" class="form-select" aria-label="Select post category">
                                        <option value="0">Open this select menu</option>
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->title }}</option>
                                        @endforeach
                                    </select>
                                    @error('category_id')
                                    <div class="text-danger">Post type should be</div>
                                    @enderror
                                </div>
                                <div class="mb-3 form-floating">
                                    <textarea name="text" class="form-control" id="postText"></textarea>
                                    <label for="postText">Post text</label>
                                    @error('text')
                                    <div class="text-danger">Post type should be</div>
                                    @enderror
                                </div>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/post/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card border border-success">
                    <div class="card-header bg-success-subtle border-success">{{ __('Edit post') }}</div>

                    <div class="card-body">
                        <div class="container py-1">

                            <div class="card-body">
                                <form action="{{ route('user.post.update', $post) }}" method="post">
                                    @method('put')
                                    @csrf
                                    <div class="mb-3 col-sm-6">
                                        <label for="title" class="form-label">Title</label>
                                        <input name="title" type="text" class="form-control" id="title"
                                               value="{{ @old('title', $post->title) }}">
                                        @error('title')
                                        <div class="text-danger">Title should be</div>
                                        @enderror
                                    </div>
                                    <div class="mb-3 ">
                                        <select name="category_id" class="form-select"
                                                aria-label="Select post category">
                                            <option value="0">Select a category</option>
                                            @foreach($categories as $category)
                                                <option
                                                    value="{{ $category->id }}" {{ $category->id === @old('category', $post->category_id) ? "selected" : "" }}>
                                                    {{ $category->title }}
                                                </option>
                                            @endforeach
                                        </select>
                                        @error('category_id')
                                        <div class="text-danger">Post type should be</div>
                                        @enderror
                                    </div>
                                    <div class="mb-3 form-floating">
                                <textarea name="text" class="form-control"
                                          id="postText">{{ @old('text', $post->text) }}</textarea>
                                        <label for="postText">Post text</label>
                                        @error('text')
                                        <div class="text-danger">Post type should be</div>
                                        @enderror
                                    </div>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
@endsection

resources/views/user/post/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card border border-success">
                    <div class="card-header bg-success-subtle border-success">{{ __('My posts') }}</div>

                    <div class="card-body">
                        <div class="container py-4">
                            @forelse($posts as $post)
                                <div class="col-md-10 border border-success border-2 mb-3 rounded-4">
                                    <div class="ms-3 mt-2">
                                        <h2><a class="link-dark text-decoration-none"
                                               href="{{ route('main.show', $post) }}">{{ $post->title }}</a></h2>
                                        <ul class="list-unstyled text-small">
                                            <li>
                                                Author: <strong>{{ $post->author->name }}</strong>,
                                                Category: <strong>{{ $post->category->title }}</strong>
                                            </li>
                                            <li>{{ $post->created_at->diffForHumans() }}</li>
                                        </ul>
                                        <h5>{{ Str::limit($post->text, 200) }}</h5>


                                        <div class="row row-cols-1 row-cols-md-2 align-items-start g-5 py-1">
                                            <div class="col d-flex flex-column align-items-start gap-2">
                                                <form method="post" class=""
                                                      action="{{ route('user.post.destroy', $post) }}">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a href="{{ route('user.post.edit', $post) }}"
                                                       class="btn btn-outline-primary">Edit</a>
                                                    <button type="submit" class="btn btn-outline-danger "
                                                            onclick=" return confirm('Are you sure you wish to delete this post ?')">
                                                        Delete
                                                    </button>
                                                </form>
                                            </div>

                                            <div class="col">
                                                <div class="container text-end">
                                                    <a class="btn btn-outline-success mb-2"
                                                       href="{{ route('main.show', $post) }}">READ MORE</a>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            @empty
                                <p class="mt-4">Other users have not created posts yet. You can be the first</p>
                            @endforelse
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/post/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card border border-success">

                    <div class="card-header bg-success-subtle border-success">
                        <a class="fw-bold link-dark text-decoration-none" href="{{ url()->previous() }}">
                            Back</a> &nbsp;/ &nbsp;My post
                    </div>

                    <div class="card-body">
                        <div class="container py-2">

                            <div class="row row-cols-1 row-cols-md-2 align-items-start g-5 py-1">
                                <div class="col d-flex flex-column align-items-start gap-2">
                                    <h1 class="text-body-emphasis">{{ $post->title }}</h1>
                                </div>

                                <div class="col text-end">

                                    <form method="post" action="{{ route('user.post.destroy', $post) }}">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{ route('user.post.edit', $post) }}" class="btn btn-outline-primary">Edit</a>
                                        <button type="submit" class="btn btn-outline-danger"
                                                onclick=" return confirm('Are you sure you wish to delete this post ?')">
                                            Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <ul class="list-unstyled text-small">
                                <li>
                                    Author: <strong>{{ $post->author->name }}</strong>,
                                    Category: <strong>{{ $post->category->title }}</strong>
                                </li>
                                <li>{{ $post->created_at->diffForHumans() }}</li>
                            </ul>
                            <p class="fs-5">{{ $post->text }}</p>

                            <form action="{{ route('user.comment.store', $post) }}" method="POST">
                                @csrf
                                <div class="w-75">
                                    <div class="form-floating">
                                    <textarea name="text" class="form-control" placeholder="Leave a comment here"
                                              id="floatingTextarea"></textarea>
                                        <label for="floatingTextarea">Comment text</label>
                                    </div>
                                </div>
                                @error('text')
                                <div class="text-danger">Write comment text</div>
                                @enderror
                                <button type="submit" class="btn btn-success mt-2">Leave Comment</button>
                            </form>
                            @if(!$comments->isEmpty())
                                <div class="my-6 p-6 bg-white border-b border-gray-200 w-75 sm:rounded-lg mt-5">
                                    <table class="table table-hover mt-6 table table-sm">
                                        <thead>
                                        <tr>
                                            <th>Author</th>
                                            <th>Comments</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @if(!empty($comments))
                                            @foreach($comments as $comment)
                                                <tr>
                                                    <th scope="col">{{ $comment->author->name }}</th>
                                                    <td class="align-middle w-100"
                                                        style="text-align: justify; max-width: 70%">
                                                        {{ $comment->text }}
                                                    </td>
                                                    <td class="align-middle text-body-secondary">
                                                        <small
                                                            class="text-body-secondary fw-semibold ps-3">{{ $comment->created_at->diffForHumans() }}
                                                        </small>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        @endif
                                        </tbody>
                                    </table>
                                </div>
                                {{ $comments->links() }}
                            @else
                                <p class="mt-4">Users have not written comments yet</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection